const Countries = {
	ABW: "Aruba",
	AFG: "Afghanistan",
	AGO: "Angola",
	AIA: "Anguilla",
	ALA: "\u00c5land Islands",
	ALB: "Albania",
	AND: "Andorra",
	ARE: "United Arab Emirates (the)",
	ARG: "Argentina",
	ARM: "Armenia",
	ASM: "American Samoa",
	ATA: "Antarctica",
	ATF: "French Southern Territories (the)",
	ATG: "Antigua and Barbuda",
	AUS: "Australia\u200a",
	AUT: "Austria",
	AZE: "Azerbaijan",
	BDI: "Burundi",
	BEL: "Belgium",
	BEN: "Benin",
	BES: "Bonaire Sint Eustatius Saba",
	BFA: "Burkina Faso",
	BGD: "Bangladesh",
	BGR: "Bulgaria",
	BHR: "Bahrain",
	BHS: "Bahamas (the)",
	BIH: "Bosnia and Herzegovina",
	BLM: "Saint Barth\u00e9lemy",
	BLR: "Belarus",
	BLZ: "Belize",
	BMU: "Bermuda",
	BOL: "Bolivia (Plurinational State of)",
	BRA: "Brazil",
	BRB: "Barbados",
	BRN: "Brunei Darussalam",
	BTN: "Bhutan",
	BVT: "Bouvet Island",
	BWA: "Botswana",
	CAF: "Central African Republic (the)",
	CAN: "Canada",
	CCK: "Cocos (Keeling) Islands (the)",
	CHE: "Switzerland",
	CHL: "Chile",
	CHN: "China",
	CIV: "C\u00f4te d'Ivoire",
	CMR: "Cameroon",
	COD: "Congo (the Democratic Republic of the)",
	COG: "Congo (the)",
	COK: "Cook Islands (the)",
	COL: "Colombia",
	COM: "Comoros (the)",
	CPV: "Cabo Verde",
	CRI: "Costa Rica",
	CUB: "Cuba",
	CUW: "Cura\u00e7ao",
	CXR: "Christmas Island",
	CYM: "Cayman Islands (the)",
	CYP: "Cyprus",
	CZE: "Czechia",
	DEU: "Germany",
	DJI: "Djibouti",
	DMA: "Dominica",
	DNK: "Denmark",
	DOM: "Dominican Republic (the)",
	DZA: "Algeria",
	ECU: "Ecuador",
	EGY: "Egypt",
	ERI: "Eritrea",
	ESH: "Western Sahara",
	ESP: "Spain",
	EST: "Estonia",
	ETH: "Ethiopia",
	FIN: "Finland",
	FJI: "Fiji",
	FLK: "Falkland Islands (the)",
	FRA: "France",
	FRO: "Faroe Islands (the)",
	FSM: "Micronesia (Federated States of)",
	GAB: "Gabon",
	GBR: "United Kingdom of Great Britain and Northern Ireland (the)",
	GEO: "Georgia",
	GGY: "Guernsey",
	GHA: "Ghana",
	GIB: "Gibraltar",
	GIN: "Guinea",
	GLP: "Guadeloupe",
	GMB: "Gambia (the)",
	GNB: "Guinea-Bissau",
	GNQ: "Equatorial Guinea",
	GRC: "Greece",
	GRD: "Grenada",
	GRL: "Greenland",
	GTM: "Guatemala",
	GUF: "French Guiana",
	GUM: "Guam",
	GUY: "Guyana",
	HKG: "Hong Kong",
	HMD: "Heard Island and McDonald Islands",
	HND: "Honduras",
	HRV: "Croatia",
	HTI: "Haiti",
	HUN: "Hungary",
	IDN: "Indonesia",
	IMN: "Isle of Man",
	IND: "India",
	IOT: "British Indian Ocean Territory (the)",
	IRL: "Ireland",
	IRN: "Iran (Islamic Republic of)",
	IRQ: "Iraq",
	ISL: "Iceland",
	ISR: "Israel",
	ITA: "Italy",
	JAM: "Jamaica",
	JEY: "Jersey",
	JOR: "Jordan",
	JPN: "Japan",
	KAZ: "Kazakhstan",
	KEN: "Kenya",
	KGZ: "Kyrgyzstan",
	KHM: "Cambodia",
	KIR: "Kiribati",
	KNA: "Saint Kitts and Nevis",
	KOR: "Korea (the Republic of)",
	KWT: "Kuwait",
	LAO: "Lao People's Democratic Republic (the)",
	LBN: "Lebanon",
	LBR: "Liberia",
	LBY: "Libya",
	LCA: "Saint Lucia",
	LIE: "Liechtenstein",
	LKA: "Sri Lanka",
	LSO: "Lesotho",
	LTU: "Lithuania",
	LUX: "Luxembourg",
	LVA: "Latvia",
	MAC: "Macao",
	MAF: "Saint Martin (French part)",
	MAR: "Morocco",
	MCO: "Monaco",
	MDA: "Moldova (the Republic of)",
	MDG: "Madagascar",
	MDV: "Maldives",
	MEX: "Mexico",
	MHL: "Marshall Islands (the)",
	MKD: "North Macedonia",
	MLI: "Mali",
	MLT: "Malta",
	MMR: "Myanmar",
	MNE: "Montenegro",
	MNG: "Mongolia",
	MNP: "Northern Mariana Islands (the)",
	MOZ: "Mozambique",
	MRT: "Mauritania",
	MSR: "Montserrat",
	MTQ: "Martinique",
	MUS: "Mauritius",
	MWI: "Malawi",
	MYS: "Malaysia",
	MYT: "Mayotte",
	NAM: "Namibia",
	NCL: "New Caledonia",
	NER: "Niger (the)",
	NFK: "Norfolk Island",
	NGA: "Nigeria",
	NIC: "Nicaragua",
	NIU: "Niue",
	NLD: "Netherlands (the)",
	NOR: "Norway",
	NPL: "Nepal",
	NRU: "Nauru",
	NZL: "New Zealand",
	OMN: "Oman",
	PAK: "Pakistan",
	PAN: "Panama",
	PCN: "Pitcairn",
	PER: "Peru",
	PHL: "Philippines (the)",
	PLW: "Palau",
	PNG: "Papua New Guinea",
	POL: "Poland",
	PRI: "Puerto Rico",
	PRK: "Korea (the Democratic People's Republic of)\u200a[o]",
	PRT: "Portugal",
	PRY: "Paraguay",
	PSE: "Palestine, State of",
	PYF: "French Polynesia",
	QAT: "Qatar",
	REU: "R\u00e9union",
	ROU: "Romania",
	RUS: "Russian Federation (the)",
	RWA: "Rwanda",
	SAU: "Saudi Arabia",
	SDN: "Sudan (the)",
	SEN: "Senegal",
	SGP: "Singapore",
	SGS: "South Georgia and the South Sandwich Islands",
	SHN: "Saint Helena\u00a0Ascension Island\u00a0Tristan da Cunha",
	SJM: "Svalbard\u00a0Jan Mayen",
	SLB: "Solomon Islands",
	SLE: "Sierra Leone",
	SLV: "El Salvador",
	SMR: "San Marino",
	SOM: "Somalia",
	SPM: "Saint Pierre and Miquelon",
	SRB: "Serbia",
	SSD: "South Sudan",
	STP: "Sao Tome and Principe",
	SUR: "Suriname",
	SVK: "Slovakia",
	SVN: "Slovenia",
	SWE: "Sweden",
	SWZ: "Eswatini",
	SXM: "Sint Maarten (Dutch part)",
	SYC: "Seychelles",
	SYR: "Syrian Arab Republic (the)",
	TCA: "Turks and Caicos Islands (the)",
	TCD: "Chad",
	TGO: "Togo",
	THA: "Thailand",
	TJK: "Tajikistan",
	TKL: "Tokelau",
	TKM: "Turkmenistan",
	TLS: "Timor-Leste",
	TON: "Tonga",
	TTO: "Trinidad and Tobago",
	TUN: "Tunisia",
	TUR: "Turkey",
	TUV: "Tuvalu",
	TWN: "Taiwan",
	TZA: "Tanzania, the United Republic of",
	UGA: "Uganda",
	UKR: "Ukraine",
	UMI: "United States Minor Outlying Islands (the)",
	URY: "Uruguay",
	USA: "United States of America (the)",
	UZB: "Uzbekistan",
	VAT: "Holy See (the)",
	VCT: "Saint Vincent and the Grenadines",
	VEN: "Venezuela (Bolivarian Republic of)",
	VGB: "Virgin Islands (British)",
	VIR: "Virgin Islands (U.S.)",
	VNM: "Viet Nam",
	VUT: "Vanuatu",
	WLF: "Wallis and Futuna",
	WSM: "Samoa",
	YEM: "Yemen",
	ZAF: "South Africa",
	ZMB: "Zambia",
	ZWE: "Zimbabwe"
};

const Currencies = {
	AED: "United Arab Emirates dirham",
	AFN: "Afghan afghani",
	ALL: "Albanian lek",
	AMD: "Armenian dram",
	ANG: "Netherlands Antillean guilder",
	AOA: "Angolan kwanza",
	ARS: "Argentine peso",
	AUD: "Australian dollar",
	AWG: "Aruban florin",
	AZN: "Azerbaijani manat",
	BAM: "Bosnia and Herzegovina convertible mark",
	BBD: "Barbados dollar",
	BDT: "Bangladeshi taka",
	BGN: "Bulgarian lev",
	BHD: "Bahraini dinar",
	BIF: "Burundian franc",
	BMD: "Bermudian dollar",
	BND: "Brunei dollar",
	BOB: "Boliviano",
	BOV: "Bolivian Mvdol",
	BRL: "Brazilian real",
	BSD: "Bahamian dollar",
	BTN: "Bhutanese ngultrum",
	BWP: "Botswana pula",
	BYN: "Belarusian ruble",
	BZD: "Belize dollar",
	CAD: "Canadian dollar",
	CDF: "Congolese franc",
	CHE: "WIR Euro",
	CHF: "Swiss franc",
	CHW: "WIR Franc",
	CLF: "Unidad de Fomento",
	CLP: "Chilean peso",
	CNY: "Renminbi yuan",
	COP: "Colombian peso",
	COU: "Unidad de Valor Real",
	CRC: "Costa Rican colon",
	CUC: "Cuban convertible peso",
	CUP: "Cuban peso",
	CVE: "Cape Verde escudo",
	CZK: "Czech koruna",
	DJF: "Djiboutian franc",
	DKK: "Danish krone",
	DOP: "Dominican peso",
	DZD: "Algerian dinar",
	EGP: "Egyptian pound",
	ERN: "Eritrean nakfa",
	ETB: "Ethiopian birr",
	EUR: "Euro",
	FJD: "Fiji dollar",
	FKP: "Falkland Islands pound",
	GBP: "Pound sterling",
	GEL: "Georgian lari",
	GHS: "Ghanaian cedi",
	GIP: "Gibraltar pound",
	GMD: "Gambian dalasi",
	GNF: "Guinean franc",
	GTQ: "Guatemalan quetzal",
	GYD: "Guyanese dollar",
	HKD: "Hong Kong dollar",
	HNL: "Honduran lempira",
	HRK: "Croatian kuna",
	HTG: "Haitian gourde",
	HUF: "Hungarian forint",
	IDR: "Indonesian rupiah",
	ILS: "Israeli new shekel",
	INR: "Indian rupee",
	IQD: "Iraqi dinar",
	IRR: "Iranian rial",
	ISK: "Icelandic króna",
	JMD: "Jamaican dollar",
	JOD: "Jordanian dinar",
	JPY: "Japanese yen",
	KES: "Kenyan shilling",
	KGS: "Kyrgyzstani som",
	KHR: "Cambodian riel",
	KMF: "Comoro franc",
	KPW: "North Korean won",
	KRW: "South Korean won",
	KWD: "Kuwaiti dinar",
	KYD: "Cayman Islands dollar",
	KZT: "Kazakhstani tenge",
	LAK: "Lao kip",
	LBP: "Lebanese pound",
	LKR: "Sri Lankan rupee",
	LRD: "Liberian dollar",
	LSL: "Lesotho loti",
	LYD: "Libyan dinar",
	MAD: "Moroccan dirham",
	MDL: "Moldovan leu",
	MGA: "Malagasy ariary",
	MKD: "Macedonian denar",
	MMK: "Myanmar kyat",
	MNT: "Mongolian tögrög",
	MOP: "Macanese pataca",
	MRU: "Mauritanian ouguiya",
	MUR: "Mauritian rupee",
	MVR: "Maldivian rufiyaa",
	MWK: "Malawian kwacha",
	MXN: "Mexican peso",
	MXV: "Mexican Unidad de Inversion",
	MYR: "Malaysian ringgit",
	MZN: "Mozambican metical",
	NAD: "Namibian dollar",
	NGN: "Nigerian naira",
	NIO: "Nicaraguan córdoba",
	NOK: "Norwegian krone",
	NPR: "Nepalese rupee",
	NZD: "New Zealand dollar",
	OMR: "Omani rial",
	PAB: "Panamanian balboa",
	PEN: "Peruvian sol",
	PGK: "Papua New Guinean kina",
	PHP: "Philippine peso",
	PKR: "Pakistani rupee",
	PLN: "Polish złoty",
	PYG: "Paraguayan guaraní",
	QAR: "Qatari riyal",
	RON: "Romanian leu",
	RSD: "Serbian dinar",
	RUB: "Russian ruble",
	RWF: "Rwandan franc",
	SAR: "Saudi riyal",
	SBD: "Solomon Islands dollar",
	SCR: "Seychelles rupee",
	SDG: "Sudanese pound",
	SEK: "Swedish krona/kronor",
	SGD: "Singapore dollar",
	SHP: "Saint Helena pound",
	SLL: "Sierra Leonean leone",
	SOS: "Somali shilling",
	SRD: "Surinamese dollar",
	SSP: "South Sudanese pound",
	STN: "São Tomé and Príncipe dobra",
	SVC: "Salvadoran colón",
	SYP: "Syrian pound",
	SZL: "Swazi lilangeni",
	THB: "Thai baht",
	TJS: "Tajikistani somoni",
	TMT: "Turkmenistan manat",
	TND: "Tunisian dinar",
	TOP: "Tongan paʻanga",
	TRY: "Turkish lira",
	TTD: "Trinidad and Tobago dollar",
	TWD: "New Taiwan dollar",
	TZS: "Tanzanian shilling",
	UAH: "Ukrainian hryvnia",
	UGX: "Ugandan shilling",
	USD: "United States dollar",
	USN: "United States dollar",
	UYI: "Uruguay Peso en Unidades Indexadas",
	UYU: "Uruguayan peso",
	UYW: "Unidad previsional",
	UZS: "Uzbekistan som",
	VES: "Venezuelan bolívar soberan",
	VND: "Vietnamese",
	VUV: "Vanuatu vatu",
	WST: "Samoan tala",
	XAF: "CFA franc BEAC",
	XAG: "Silver",
	XAU: "Gold",
	XBA: "European Composite Unit",
	XBB: "European Monetary Unit",
	XBC: "European Unit of Account 9",
	XBD: "European Unit of Account 17",
	XCD: "East Caribbean dollar",
	XDR: "Special drawing rights",
	XOF: "CFA franc BCEAO",
	XPD: "Palladium",
	XPF: "CFP franc",
	XPT: "Platinum",
	XSU: "SUCRE",
	XTS: "Code reserved for testing",
	XUA: "ADB Unit of Account",
	XXX: "No currency",
	YER: "Yemeni rial",
	ZAR: "South African rand",
	ZMW: "Zambian kwacha",
	ZWL: "Zimbabwean dollar"
}

const Types = {
	account_type: {
		type: 'enum',
		validValues: [
			'STANDARD',
			'BUSINESS',
			'PARTNER'
		]
	},
	account_status: {
		type: 'enum',
		validValues: [
			'ACTIVE',
			'INACTIVE',
			'KYC_REQUIRED',
			'SUSPENDED'
		]
	},
	account_kyc_level: {
		type: 'enum',
		validValues: [
			'LEVEL_0',
			'LEVEL_1',
			'LEVEL_2',
			'LEVEL_3'
		]
	},
	date: {
		type: 'special',
		validate: (date) => {
			return (date instanceof Date && !isNaN(date));
		}
	},
	business_type: {
		type: 'enum',
		validValues: [
			'COMPANY',
			'ASSOCIATION',
			'SOLE_TRADER'
		]
	},
	phone_number: {
		type: 'string',
		maxLength: 64,
		pattern: /^[0-9]+$/
	},
	country: {
		type: 'enum',
		validValues: Object.keys(Countries)
	},
	representative: {
		type: 'object',
		fields: {
			lastname: {
				type: 'string',
				maxLength: 64,
				required: true,
			},
			firstname: {
				type: 'string',
				maxLength: 64,
				required: true,
			},
			birthdate: {
				type: 'date',
				required: true
			},
			nationality: {
				type: 'country',
				required: true
			}
		}
	},
	subscriber: {
		type: 'extends',
		object: 'representative',
		fields: {
			citizen_us: {
				type: 'boolean',
				required: false
			},
			fiscal_us: {
				type: 'boolean',
				required: false
			},
			fiscal_out_france: {
				type: 'boolean',
				required: false
			}
		}
	},
	address: {
		type: 'object',
		fields: {
			label1: {
				type: 'string',
				maxLength: 64,
				required: true
			},
			label2: {
				type: 'string',
				maxLength: 64,
				required: false
			},
			label3: {
				type: 'string',
				maxLength: 64,
				required: false
			},
			zip_code: {
				type: 'string',
				maxLength: 10,
				required: true
			},
			city : {
				type: 'string',
				maxLength:100,
				required: true
			}
		}
	}
}

const validate = (type, object) => {
	if (null == Types[type])
		throw new Error(`Unknown type ${type}`);
	const objectDescriptor = Types[type]
	if (objectDescriptor.type === 'object') {
		if (null == objectDescriptor.fields)
			throw new Error(`Descriptor for type "object" must have a property "fields"`);
		for (let i in objectDescriptor.fields) {
			const field = objectDescriptor.fields[i];
		}
	}
}
